name: Deploy
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - run: |
          git diff-tree --no-commit-id --name-only -r HEAD~1 HEAD  > changed_files.txt
          cat changed_files.txt

      - run: |
          grep -E 'schema.prisma|pnpm-lock.yaml|deploy.yml' changed_files.txt > filtered_files.txt || true
          cat filtered_files.txt

      - id: check_changes
        run: |
          cat filtered_files.txt
          if [[ -s "filtered_files.txt" ]]; then
            echo "::set-output name=changes_exist::true"
          else
            echo "::set-output name=changes_exist::false"
          fi

      - name: Set tar name
        id: my_vars
        run: |
          echo "::set-output name=tar_name::$(date +'%Y%m%dT%H%M%S')-$(echo $GITHUB_SHA | cut -c 1-7)"

      # libquery_engine 体积太大不打包，存储到 cos 上直接下载到指定为止
      - name: Tar artifact
        run: |
          tar --exclude .git --exclude .github --exclude "libquery_engine-*.so.node" -czf ${{ runner.temp }}/${{ steps.my_vars.outputs.tar_name }}.tar.gz .

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.my_vars.outputs.tar_name }}
          path: ${{ runner.temp }}/${{ steps.my_vars.outputs.tar_name }}.tar.gz

      - name: Set ssh
        run: |
          echo "${{ secrets.SERVER_KEY }}" > ${{ runner.temp }}/private_key.pem
          chmod 600 ${{ runner.temp }}/private_key.pem
          mkdir ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keygen -y -f ${{ runner.temp }}/private_key.pem > ${{ runner.temp }}/private_key.pub
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - run: |
          scp -i ${{ runner.temp }}/private_key.pem ${{ runner.temp }}/${{ steps.my_vars.outputs.tar_name }}.tar.gz ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/cms/cms-admin-api

      - name: Extract
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            mkdir /cms/cms-admin-api/${{ steps.my_vars.outputs.tar_name }}
            tar -xzvf ${{ steps.my_vars.outputs.tar_name }}.tar.gz -C /root/cms/cms-admin-api/${{ steps.my_vars.outputs.tar_name }}

      - name: Reinstall
        if: steps.check_changes.outputs.changes_exist == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cp /root/cms/cms-admin-api/${{ steps.my_vars.outputs.tar_name }}/package.json release/package.json
            cp /root/cms/cms-admin-api/${{ steps.my_vars.outputs.tar_name }}/pnpm-lock.yml release/pnpm-lock.yml
            cd /root/cms/cms-admin-api/release && pnpm install --registry=https://registry.npmmirror.com
            cp -r /root/cms/cms-admin-api/${{ steps.my_vars.outputs.tar_name }}/node_modules/@prisma /root/cms/cms-admin-api/release/node_modules
            wget -P /root/cms/cms-admin-api/release/node_modules/@prisma/client-cms_admin/ https://common-1306445775.cos.ap-shanghai.myqcloud.com/libquery_engine/libquery_engine-rhel-openssl-1.0.x.so.node
            touch /root/cms/cms-admin-api/release/${{ steps.my_vars.outputs.tar_name }}-pnpm-install.txt

      - name: Restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cp /root/cms/cms-admin-api/${{ steps.my_vars.outputs.tar_name }}/main.js /root/cms/cms-admin-api/release
            cp /root/cms/cms-admin-api/${{ steps.my_vars.outputs.tar_name }}/main.js.map /root/cms/cms-admin-api/release
            touch /root/cms/cms-admin-api/release/${{ steps.my_vars.outputs.tar_name }}.txt
            pm2 restart cms-admin-api
